### PR TITLE
added some outlines - DO NOT CLOSE PR

### PR DESCRIPTION
**Pull request by SomeOrdinaryBro**
will add more content today - im in the process of writing I/O atm. once that is done will finsh httpvsS and API

### CODE REVIEW

**Comment by SomeOrdinaryBro** [comment]
Unless you have anything important to update - plesae do not close this.. Thank you

**Comment by SomeOrdinaryBro** [comment]
@mshajid merge this pull request please. Thank you!

**Review by mshajid — APPROVED** [review]
Everything is good. Perfecto.

**Review by mshajid — COMMENTED** [review]
Let me know once you complete this section.

**Pull request merged**
